- name: "upgrade packages."
  become: true
  apt:
    upgrade: "yes"

- name: "install dependencies - nodejs"
  become: true
  apt:
    name: nodejs
    update_cache: yes
    
- name: "install dependencies - npm"
  become: true
  apt:
    name: npm
    update_cache: yes  
#    state: latest

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Creates directory
  file:
    path: /home/ubuntu/backend
    state: directory

- name: Copy backend dist files web server
  copy:
    src: /root/project/artifact.tar.gz
    dest: /home/ubuntu/backend/artifact.tar.gz

- name: Uncompress Backend
  shell: |
    cd /home/ubuntu/backend
    tar xvzf artifact.tar.gz -C .
    ls -la

- name: Build
  become: true
  shell: |
    cd /home/ubuntu/backend
    npm install
    npm run build

- name: Start PM2
  shell: |
    cd /home/ubuntu/backend